---
# Tasks: Firewall
#
# Adjust firewall settings
#

- name: "firewall - open ports"
  win_firewall_rule:
      name: Ansible - Allow TCP Port {{ item }}
      localport: "{{ item }}"
      action: allow
      direction: in
      protocol: tcp # tcp, udp, any
      enabled: yes
      state: present
  with_items:
    - 80 # http
    - 445 # smb
