---
  dependency:
    name: galaxy
  driver:
    name: vagrant
    provider:
      name: virtualbox
      options:
        cpus: 2
  platforms:
    - name: windows-2019
      box: gusztavvargadr/windows-server
      provider_raw_config_args:
        - "memory = '2048'"
        - "linked_clone = false"
  provisioner:
    name: ansible
    connection_options:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_port: 55985
      ansible_host: 127.0.0.1
      ansible_connection: winrm
      ansible_winrm_scheme: http
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
      ansible_shell_type: powershell
  verifier:
   name: ansible
  lint: |
    set -e
    yamllint .
    ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    ansible-lint .

  # verifier:
  #   name: testinfra
  #   directory: tests/
  #   enabled: true
  #   env:
  #     PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  #   options:
  #     v: 1 # show which tests where executed in test output